FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
COPY shared/package*.json ./shared/
COPY frontend/package*.json ./frontend/
RUN npm install
COPY shared ./shared
COPY frontend ./frontend
RUN npm run build --workspace=shared
RUN npm run build --workspace=frontend

FROM node:18-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/frontend/.next ./frontend/.next
COPY --from=builder /app/frontend/public ./frontend/public
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/frontend/package.json ./frontend/package.json

EXPOSE 3000
CMD ["npm", "run", "start", "--workspace=frontend"]
